port module InteropPorts exposing (fromElm, decodeFlags)

{-| This file was generated by elm-ts-interop init. You can manually edit this file,
just avoid exposing the low-level ports to ensure that only the FromElm and ToElm types
can be sent/received by your ports.

@docs fromElm, toElm, decodeFlags

-}

import InteropDefinitions
import Json.Decode as Decode
import Json.Encode as Encode
import TsJson.Decode as TsDecode
import TsJson.Encode as TsEncode


{-| -}
fromElm : InteropDefinitions.FromElm -> Cmd msg
fromElm value =
    value
        |> (InteropDefinitions.interop.fromElm |> TsEncode.encoder)
        |> interopFromElm


{-| -}
decodeFlags : Decode.Value -> Result Decode.Error InteropDefinitions.Flags
decodeFlags flags =
    Decode.decodeValue
        (InteropDefinitions.interop.flags |> TsDecode.decoder)
        flags



-- INTERNALS - do not expose


port interopFromElm : Encode.Value -> Cmd msg
